apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-ingress
spec:
  tls:
    - hosts:
        - staging.learn.alecloud.site
      secretName: lms-tls-staging
  rules:
    - host: staging.learn.alecloud.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lms
                port:
                  number: 8000
