apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openedx-media-pvc
  namespace: openedx
spec:
  accessModes: [ReadWriteMany]
  storageClassName: efs-shared
  resources:
    requests:
      storage: 100Gi
