apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openedx-aws-secrets
  namespace: openedx
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "openedx-prod/db-credentials"
        objectType: "secretsmanager"
        objectAlias: "db-credentials"
        jmesPath:
          - path: "password"
            objectAlias: "db-password"
          - path: "host"
            objectAlias: "db-host"
          - path: "port"
            objectAlias: "db-port"
      - objectName: "openedx-prod/redis/auth-token"
        objectType: "secretsmanager"
        objectAlias: "redis-auth-token"
      - objectName: "openedx-prod/django-secret-key"
        objectType: "secretsmanager"
        objectAlias: "django-secret-key"
  secretObjects:
    - secretName: openedx-db-secret
      type: Opaque
      data:
        - objectName: db-password
          key: password
        - objectName: db-host
          key: host
        - objectName: db-port
          key: port
    - secretName: openedx-redis-secret
      type: Opaque
      data:
        - objectName: redis-auth-token
          key: REDIS_AUTH_TOKEN
    - secretName: openedx-django-secret
      type: Opaque
      data:
        - objectName: django-secret-key
          key: secret-key
