apiVersion: v1
kind: ServiceAccount
metadata:
  name: openedx-sa
  namespace: openedx
  labels:
    app: openedx
  annotations:
    # FILL: terraform -chdir=infra/live/prod/platform output openedx_s3_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::119778517587:role/openedx-prod-openedx-s3-role"
automountServiceAccountToken: false
