apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
spec:
  replicas: 1
